[book]
title = "go4clouds Kubernetes Tutorial"
description = "**go4clouds** is open source Kubernetes tutorial for application developers"
authors = ["Michal Jura"]
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/go4clouds/docs"
git-repository-icon = "fa-github"
site-url = "/"

[rust]
edition = "2018"

